import { assert, nowIso, uuid } from '../db';
import { BaseService, reqStr, str } from './base';

/*
 * Secrets are AES-GCM encrypted with a key derived from JWT_SECRET, byte-compatible with
 * the legacy app's src/lib/crypto.ts, so existing rows decrypt unchanged.
 */
const enc = new TextEncoder();
const keyFor = (secret: string) =>
  crypto.subtle.importKey('raw', enc.encode(secret.padEnd(32, '0').slice(0, 32)), { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);

async function encrypt(text: string, secret: string) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const data = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await keyFor(secret), enc.encode(text)));
  const combined = new Uint8Array(iv.length + data.length);
  combined.set(iv);
  combined.set(data, iv.length);
  return btoa(String.fromCharCode(...combined));
}

async function decrypt(base64: string, secret: string) {
  const bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0));
  const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: bytes.slice(0, 12) }, await keyFor(secret), bytes.slice(12));
  return new TextDecoder().decode(plain);
}

const cleanSecret = (s: string) => s.replace(/[\s=-]/g, '').toUpperCase();
const isBase32 = (s: string) => /^[A-Z2-7]{16,}$/.test(s);

/** RFC 6238 TOTP (SHA-1, 6 digits, 30 s), as generated by the legacy `otpauth` defaults. */
async function totp(secret: string, at = Date.now()) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = '';
  for (const ch of secret) bits += alphabet.indexOf(ch).toString(2).padStart(5, '0');
  const key = await crypto.subtle.importKey('raw', Uint8Array.from(bits.match(/.{8}/g) || [], b => parseInt(b, 2)), { name: 'HMAC', hash: 'SHA-1' }, false, ['sign']);
  const counter = new Uint8Array(8);
  new DataView(counter.buffer).setUint32(4, Math.floor(at / 30000));
  const sig = new Uint8Array(await crypto.subtle.sign('HMAC', key, counter));
  const o = sig[sig.length - 1] & 15;
  const bin = ((sig[o] & 127) << 24) | (sig[o + 1] << 16) | (sig[o + 2] << 8) | sig[o + 3];
  return (bin % 1000000).toString().padStart(6, '0');
}

interface SecretRow { id: string; accountName: string; secret: string; category: string | null; icon: string | null; createdAt: string }

export class TwoFactorService extends BaseService {
  private get key() {
    return this.env.JWT_SECRET || null;
  }

  /**
   * The plaintext secret, or null unless it genuinely decrypted to Base32. Unlike the legacy
   * decryptText, a failure never falls back to the ciphertext, which would yield plausible but
   * wrong codes. Neither the ciphertext nor the plaintext is ever logged.
   */
  private async reveal(ciphertext: string) {
    try {
      const secret = cleanSecret(await decrypt(ciphertext, this.key!));
      return isBase32(secret) ? secret : null;
    } catch {
      return null;
    }
  }

  async list() {
    const rows = await this.db.all<SecretRow>('SELECT * FROM TwoFactorSecret WHERE userId = ? ORDER BY createdAt DESC', this.user.id);
    const now = Date.now();
    // Each row settles on its own: a row that fails to decrypt is flagged, never fatal to the list.
    const accounts = await Promise.all(rows.map(async r => {
      let token: string | null = null, nextToken: string | null = null, undecryptable = false;
      if (this.key) {
        const secret = await this.reveal(r.secret);
        if (secret) [token, nextToken] = await Promise.all([totp(secret, now), totp(secret, now + 30000)]);
        else undecryptable = true;
      }
      return { id: r.id, accountName: r.accountName, category: r.category || 'Other', icon: r.icon, token, nextToken, undecryptable };
    }));
    return { locked: !this.key, period: 30, generatedAt: now, accounts };
  }

  async create(args: { accountName?: unknown; secret?: unknown; category?: unknown; icon?: unknown }) {
    assert(this.key, 503, 'The encryption key (JWT_SECRET) is not configured for this deployment.');
    const secret = cleanSecret(String(args.secret ?? ''));
    assert(isBase32(secret), 400, 'Enter a valid Base32 secret, at least 16 characters.');
    const now = nowIso();
    await this.db.run(
      'INSERT INTO TwoFactorSecret (id, userId, accountName, secret, createdAt, updatedAt, category, icon) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
      uuid(), this.user.id, reqStr(args.accountName, 'Account name', 120), await encrypt(secret, this.key), now, now,
      (str(args.category, 60) || '').trim() || 'Other', (str(args.icon, 60) || '').trim() || null,
    );
    return { success: true };
  }

  async update(args: { id?: unknown; accountName?: unknown; category?: unknown; icon?: unknown; secret?: unknown }) {
    const row = await this.owned<SecretRow>('TwoFactorSecret', args.id, 'Account');
    const patch: Record<string, unknown> = {
      accountName: args.accountName === undefined ? undefined : reqStr(args.accountName, 'Account name', 120),
      category: args.category === undefined ? undefined : (str(args.category, 60) || '').trim() || 'Other',
      icon: args.icon === undefined ? undefined : (str(args.icon, 60) || '').trim() || null,
      updatedAt: nowIso(),
    };
    if (typeof args.secret === 'string' && args.secret.trim()) {
      assert(this.key, 503, 'The encryption key (JWT_SECRET) is not configured for this deployment.');
      const secret = cleanSecret(args.secret);
      assert(isBase32(secret), 400, 'Enter a valid Base32 secret, at least 16 characters.');
      patch.secret = await encrypt(secret, this.key);
    }
    await this.db.update('TwoFactorSecret', row.id, patch);
    return { success: true };
  }

  async remove(args: { id?: unknown }) {
    const row = await this.owned<SecretRow>('TwoFactorSecret', args.id, 'Account');
    await this.db.run('DELETE FROM TwoFactorSecret WHERE id = ?', row.id);
    return { success: true };
  }
}
